package de.tentact.languageapi.file;

import org.jetbrains.annotations.NotNull;

import java.nio.file.Path;
import java.util.Locale;
import java.util.concurrent.CompletableFuture;

public interface FileHandler {

  /**
   * Loads all translations from a file that was generated by the LanguageAPI
   *
   * @param path the path to the file
   * @return whether the import was successful or not
   */
  CompletableFuture<Boolean> loadFile(@NotNull Path path);

  /**
   * Loads all translations from a file that was generated by the LanguageAPI
   *
   * @param path      the path to the file
   * @param overwrite whether existing translations should be overwritten
   * @return whether the import was successful or not
   */
  CompletableFuture<Boolean> loadFile(@NotNull Path path, boolean overwrite);

  /**
   * Exports a locale to the default destination (plugins/LanguageAPI/export)
   *
   * @param locale the locale to be exported
   * @return whether the locale was exported successfully
   */
  CompletableFuture<Boolean> exportLanguage(@NotNull Locale locale);

  /**
   * Exports a locale to the default destination (plugins/LanguageAPI/export)
   *
   * @param locale the locale to be exported
   * @param path   the destination of the file
   * @return whether the locale was exported successfully
   */
  CompletableFuture<Boolean> exportLanguage(@NotNull Locale locale, @NotNull Path path);

}
